version: "3.8"

services:
  app:
    build: .
    container_name: minha-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/minha_base
      - SPRING_DATASOURCE_USERNAME=meu_usuario
      - SPRING_DATASOURCE_PASSWORD=minha_senha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: meu-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: minha_base
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
