version: '3.8'

services:
  app:
    image: seuusuario/seuapp:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seubanco
      SPRING_DATASOURCE_USERNAME: meu_usuario
      SPRING_DATASOURCE_PASSWORD: minha_senha
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: seuusuario
      POSTGRES_PASSWORD: suasenha
      POSTGRES_DB: seubanco
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
